### PR TITLE
Added in focus to tree view

### PR DESCRIPTION
**Pull request by nova4005**
I worked on adding in the focus highlighting for the tree view when toggling ctrl+0 for directories and files.

### CODE REVIEW

**Comment by trevordmiller** [comment]
Resolves #17

**Comment by nova4005** [comment]
I made those changes and added the short video for showing the effects of the focus switching on toggle. Let me know if this works or if there is something else I can do to help.

**Comment by trevordmiller** [comment]
@nova4005 Thanks! Sorry, I didn't mean a video in the commit itself - just on this pull request to show the changes without people needing to checkout out your fork. I did watch the video and it looks great though so if you'll just remove that video, I'll merge this in. Thank you.

**Comment by nova4005** [comment]
Sorry about that, I have removed the video.

**Comment by nova4005** [comment]
tree-view-focus_v3

**Comment by trevordmiller** [comment]
@nova4005 No worries! Thank you.

**Comment by trevordmiller** [comment]
It has been released: 
image

**Pull request merged**
